version: "3.7"
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    volumes:
      - ./website:/var/www/html/
    restart: unless-stopped
    networks:
      - phishingDB
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "ohHnP9RaU8gRKWi@FvwaLsFGfUieiSy"
      MYSQL_DATABASE: phishingDB
      MYSQL_USER: evKqe7NcT#wtnCuTT&v5!L7eWbCqqH^S
      MYSQL_PASSWORD: 6v7HABYQKRjhbnJvuBa6ZvU*UayvDTBM
    volumes:
      - ./phishingDB:/var/lib/mysql
    restart: unless-stopped
    networks:
      - phishingDB
networks:
  phishingDB:
    driver: bridge
